services: 
  calculator: 
    container_name: exu2-calculadoras
    image: calculators:v1.0.1
    build:
      context: ./client
      args:
        API_URL: http://localhost:8081/api-calc/suma
    ports:
      - "80:80"
    networks:
      - exu2-rvrh-net

  operations: 
    container_name: exu2-operacioness
    image: operationss:v1.0.1
    build:
      context: ./server
    environment:
      SERVER_PORT: 8080
    ports:
      - "8082:8080"
    networks:
      - exu2-rvrh-net

networks:
  exu2-rvrh-net:
    external: true